#!/bin/bash
echo $((POWER / DIVIDE))
[master 530ffce] Write a script that prints the result of POWER divided by DIVIDE, followed by a new line. POWER and DIVIDE are environment variables
 1 file changed, 2 insertions(+)
 create mode 100755 0x03-shell_variables_expansions/9-divide_and_rule
